name: cron-daily-testing

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL everyday
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-ancient-lake-3589.fly.dev/