name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
      - name: Give today's date
        run: |
          date
      - name: Give current directory content
        run: |
          ls


