name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  # hello_world_job:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Say hello
  #       run: |
  #         echo "Hello World"
  #     - name: Give today's date
  #       run: |
  #         date
  #     - name: Give current directory content
  #       run: |
  #         ls
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: lint
        run: |
          npm run eslint
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm run test
  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu 20.04
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        with:
          tag_prefix: "v"
          release_branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

        # code delete