name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: lint
        run: |
          npm run eslint
      - name: build
        run: |
          npm run build
      - name: test
        run: |
          npm run test
      # smallish test added here. no /github. have secret and webhook added on github
      - name: Debug Webhook URL Unmasked
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: echo "$WEBHOOK"
    
      - name: Discord Success Notification
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "Bot", "avatar_url": "https://example.com/avatar.png", "content": "The project was successfully deployed at ..."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Discord Failure Notification
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "Bot", "avatar_url": "https://example.com/avatar.png", "content": "The project failed to deploy at ...."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
      
        
      - name: Discord Success Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: 'info'
          details: |
            '✅ **Health Check Passed!**
              Application: [Link](https://full-stack-open-pokedex-lygk.onrender.com/)
              Time: 0 * * * *
              Status: Healthy'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DEBUG: true

              
      - name: Discord Failure Notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          {
            severity: 'error',
            details: 'The project  failed to deploy at ....',
            webhookUrl: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          }



  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
  tag_release:
    env:
      CONDITION: ${{ !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    needs: simple_deployment_pipeline
    runs-on: ubuntu 20.04
    if: ${{ github.env.CONDITION }}
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        with:
          tag_prefix: "v"
          release_branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch



  # hello_world_job:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Say hello
  #       run: |
  #         echo "Hello World"
  #     - name: Give today's date
  #       run: |
  #         date
  #     - name: Give current directory content
  #       run: |
  #         ls